project:
  type: website
  output-dir: docs
  resources:
    - CNAME
    
execute:
  freeze: auto

website:
  title: "Maris Collaborative, LLC"
  favicon: $brand-small
  site-url: "https://www.mariscollaborative.com"
  navbar:
    logo: $brand-full
    right: # align navbar items to the right/left/center
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

