project:
  type: website
  output-dir: docs
  resources:
    - CNAME
    
execute:
  freeze: auto

website:
  title: "Maris Collaborative, LLC"
  # favicon: logos/icon.png
  site-url: "https://www.mariscollaborative.com"
  repo-url: https://github.com/AngeliaMiller/maris-collaborative
  navbar:
    title: false
    #logo: logos/mc-logo-hex.png
    #logo-alt: "Maris Collaborative with wave icon"
    right: # align navbar items to the right/left/center
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
  page-footer:
    # background: light
    left: Copyright 2025
    right: This website is built with [Quarto](https://quarto.org/)
      
# Use the brand file for all documents in the project
brand: _brand.yml


format:
  html:
    theme:
      - cosmo
      - brand
      - mystyles.scss
    # css: styles.css
    toc: true

editor: visual


