project:
  type: website
  output-dir: docs
  resources:
    - CNAME
    
execute:
  freeze: auto

website:
  # title: "Maris Collaborative, LLC"
  # favicon: logos/icon.png
  site-url: "https://www.mariscollaborative.com"
  navbar:
    logo: logos/full-logo.png
    logo-alt: "Maris Collaborative with wave icon"
    right: # align navbar items to the right/left/center
      - href: index.qmd
        text: Home
      - about.qmd
      
# Use the brand file for all documents in the project
brand: _brand.yml

format:
  html:
    theme:
      - cosmo
      - brand
      - styles.css
    css: styles.css
    toc: true

editor: visual

