project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  title: "Maris Collaborative, LLC"
  site-url: "https://mariscollaborative.com"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

