project:
  type: website
  output-dir: docs
  resources:
    - CNAME
    
execute:
  freeze: auto

website:
  title: "Maris Collaborative, LLC"
  # favicon: logos/icon.png
  site-url: "https://www.mariscollaborative.com"
  # repo-url: "https://github.com/AngeliaMiller/maris-collaborative"
  navbar:
    title: false
    #logo: logos/mc-logo-hex.png
    #logo-alt: "Maris Collaborative with wave icon"
    right: # align navbar items to the right/left/center
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: contact.qmd
        text: Contact 
    tools:
      # - icon: "linkedin"
        # href: https://www.linkedin.com/in/angeliamarie4/
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/AngeliaMiller/maris-collaborative
          - text: Report a Bug
            href: https://github.com/AngeliaMiller/maris-collaborative/issues
      # - icon: envelope
        # href: mailto:amiller@mariscollaborative.com
  google-analytics: "G-78H09DJ36Z"
  page-footer:
    background: light
    left: Copyright 2025
    right: This website is built with [Quarto](https://quarto.org/)
      
# Use the brand file for all documents in the project
brand: _brand.yml


format:
  html:
    page-layout: full
    theme:
      - cosmo
      - brand
      - mystyles.scss
    # css: styles.css
    toc: true
    include-in-header: 
      - text: | 
      <script async src="https://www.googletagmanager.com/gtag/js?id=G-78H09DJ36Z"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-78H09DJ36Z');
</script>

editor: visual


